language: java

jdk:
- oraclejdk8

sudo: false

# Build everything in 'script' phase
install: /bin/true

script:
  - mvn clean install -X

cache:
  directories:
    - '$HOME/.m2/repository'

branches:
  only:
    - master
